#!/usr/bin/env python3
"""Generate projects.html and backlog.html from projects.json.

Single source of truth is projects.json. Edit it, then run:

    python3 build_projects.py

Output is static HTML (native <details> for collapse, zero JS) matching the
site's terminal aesthetic in styles.css. Re-runnable / idempotent.
"""
import json
import html
import os

HERE = os.path.dirname(os.path.abspath(__file__))
DATA = os.path.join(HERE, "projects.json")

GENERATED_NOTE = "<!-- GENERATED by build_projects.py from projects.json - do not edit by hand -->"

# Editorial timeline strip (presentation, not data): one line per era.
TIMELINE = [
    ("2025 Q1", "Automation sprint - a burst of Python/Bash CLI tools that coalesced into Briefer."),
    ("2026 Q1", "First native desktop app in Rust (ollama-native)."),
    ("2026 Q2", "Flutter app suite (Industria, Indicium, Anetmon, Sentry, Tutor) + self-hosted F-Droid distribution."),
]


def esc(s):
    return html.escape(str(s), quote=True)


def sortable(date):
    """'YYYY-MM-DD' or 'YYYY-MM' -> comparable string."""
    return date if len(date) == 10 else date + "-01"


def latest_date(project):
    ms = project.get("milestones", [])
    if ms:
        return max(sortable(m["date"]) for m in ms)
    return sortable(project.get("last_active", "0000-00"))


def page_shell(title, nav_html, body_html):
    return f"""{GENERATED_NOTE}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{esc(title)}</title>
    <link rel="stylesheet" href="./styles.css">
</head>
<body class="doc">
    <header>
        <h1>{esc(title)}</h1>
    </header>
    <nav class="topnav">{nav_html}</nav>
{body_html}
</body>
</html>
"""


def render_milestone(m):
    date = esc(m["date"])
    ver = f' <span class="ver">v{esc(m["version"])}</span>' if m.get("version") else ""
    note = f' {esc(m["note"])}' if m.get("note") else ""
    return f'        <li><span class="date">{date}</span>{ver}{note}</li>'


def render_project(p):
    name = esc(p["name"])
    codename = f' <span class="codename">({esc(p["codename"])})</span>' if p.get("codename") else ""
    status = esc(p.get("status", ""))
    span = f'{esc(p.get("started",""))}–{esc(p.get("last_active",""))}'
    tech = ", ".join(esc(t) for t in p.get("tech", []))
    meta = f'[{status} · {span} · {tech}]'
    summary = esc(p.get("summary", ""))

    milestones = sorted(p.get("milestones", []), key=lambda m: sortable(m["date"]), reverse=True)
    ms_html = "\n".join(render_milestone(m) for m in milestones)

    roadmap = ""
    if p.get("roadmap"):
        items = "; ".join(esc(r) for r in p["roadmap"])
        roadmap = f'\n      <p class="roadmap">Planned: {items}</p>'

    return f"""    <details class="project status-{status}">
      <summary><span class="pname">{name}</span>{codename} &mdash; <span class="psum">{summary}</span> <span class="meta">{meta}</span></summary>
      <ul class="milestones">
{ms_html}
      </ul>{roadmap}
    </details>"""


def build_projects(data):
    projects = sorted(data["projects"], key=latest_date, reverse=True)

    timeline = "\n".join(
        f'        <li><span class="date">{esc(period)}</span> {esc(text)}</li>'
        for period, text in TIMELINE
    )

    cards = "\n".join(render_project(p) for p in projects)

    exps = sorted(data.get("experiments", []), key=lambda e: sortable(e.get("date", "0000-00")), reverse=True)
    exp_items = "\n".join(
        f'        <li><span class="date">{esc(e.get("date",""))}</span> {esc(e["name"])}'
        + (f' &mdash; {esc(e["note"])}' if e.get("note") else "") + "</li>"
        for e in exps
    )

    body = f"""    <main class="doc-main">
      <p class="lead"># Projects, newest first. Each expands to its history.</p>

      <section class="timeline">
        <h2>Timeline</h2>
        <ul>
{timeline}
        </ul>
      </section>

      <section class="projects">
{cards}
      </section>

      <section class="experiments">
        <details>
          <summary>Experiments &amp; one-offs ({len(exps)})</summary>
          <ul>
{exp_items}
          </ul>
        </details>
      </section>
    </main>"""

    nav = '<a href="index.html">Home</a> &middot; <a href="backlog.html">Backlog</a> &middot; <a href="autogit.html">Auto git pusher</a>'
    return page_shell("Projects", nav, body)


def build_backlog(data):
    items = "\n".join(
        f'        <li>{esc(b["name"])}'
        + (f' <span class="tag">[{esc(b["project"])}]</span>' if b.get("project") else "")
        + (f' &mdash; {esc(b["note"])}' if b.get("note") else "") + "</li>"
        for b in data.get("backlog", [])
    )
    body = f"""    <main class="doc-main">
      <p class="lead"># Future ideas &amp; unstarted work.</p>
      <ul class="backlog">
{items}
      </ul>
    </main>"""
    nav = '<a href="index.html">Home</a> &middot; <a href="projects.html">Projects</a>'
    return page_shell("Backlog", nav, body)


def main():
    with open(DATA, encoding="utf-8") as f:
        data = json.load(f)
    with open(os.path.join(HERE, "projects.html"), "w", encoding="utf-8") as f:
        f.write(build_projects(data))
    with open(os.path.join(HERE, "backlog.html"), "w", encoding="utf-8") as f:
        f.write(build_backlog(data))
    print("Wrote projects.html and backlog.html from projects.json")


if __name__ == "__main__":
    main()
